{
 "title": "Coraza WAF",
 "description": "Coraza Web Application Firewall",
 "tags": [
  "firewall",
  "waf",
  "coraza"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "loki" },
   { "name": "transid", "label": "TX" }
  ]
 },
 "panels": [
  {
   "title": "Blocked Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {job=\"corazawaf\"}\n      | json\n      [5m]\n  )\n)",
     "legendFormat": "{{transaction_request_method}}"
    }
   ]
  },
  {
   "title": "HTTP Method",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"corazawaf\"} | json [$__interval])) by (transaction_request_method)",
     "legendFormat": "{{transaction_request_method}}"
    }
   ]
  },
  {
   "title": "URI",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"corazawaf\"} | json [$__interval])) by (transaction_request_uri)",
     "legendFormat": "{{transaction_request_uri}}"
    }
   ]
  },
  {
   "title": "Rules Hit",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"corazawafmessages\"} | json | data_severity > 0 [$__interval])) by (data_id)",
     "legendFormat": "{{transaction_client_ip}}"
    }
   ]
  },
  {
   "title": "Client IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"corazawaf\"} | json [$__interval])) by (transaction_client_ip)",
     "legendFormat": "{{transaction_client_ip}}"
    }
   ]
  },
  {
   "title": "Host IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"corazawaf\"} | json [$__interval])) by (transaction_host_ip)",
     "legendFormat": "{{transaction_host_ip}}"
    }
   ]
  },
  {
   "title": "Host Port",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"corazawaf\"} | json [$__interval])) by (transaction_host_port)",
     "legendFormat": "{{transaction_host_port}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{job=\"corazawaf\"} | json | line_format \"| {{.transaction_id}} | {{.transaction_client_ip}} | {{.transaction_request_method}} {{.transaction_request_uri}}\""
    }
   ]
  },
  {
   "title": "Transaction Details    ℹ️ insert transaction id at TX",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{job=\"corazawafmessages\"} | json | transaction_id=\"${transid}\" | data_severity > 0 or data_id = \"980170\"",
     "resolution": 1
    }
   ]
  }
 ]
}